import type { ApprovalItem } from "./types";

export const INITIAL_APPROVALS: ApprovalItem[] = [
  // Column 1: Onay bekleniyor
  {
    id: "demo-1",
    title: "O'dan M'ye, M'den G'ye... Arkadaşlarınızla harika vakit...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "00:54",
    fullDateLabel: "5 Eylül, 00:54",
    imageUrl: "/images/approvals/grapefruit_citrus.jpg",
    isCarousel: true,
    caption: "O'dan M'ye, M'den G'ye... Arkadaşlarınızla harika vakit geçirmek için taze sıkılmış Jusco narenciye ferahlığı yanınızda! 🍊✨",
    status: "NEEDS_REVIEW",
    statusLabel: "Askıda olması",
    campaignName: "Sonbahar Lansmanı",
    tags: ["narenciye", "fresh", "ferahlik"],
    platform: "facebook",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-2",
    title: "Yeni lezzetler denemek için iyi bir zaman mı? 😋 Evet! ...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 20:54",
    fullDateLabel: "5 Eylül, 20:54",
    imageUrl: "/images/approvals/papaya_seeds.jpg",
    caption: "Yeni lezzetler denemek için iyi bir zaman mı? 😋 Evet! Jusco'nun yepyeni egzotik papaya & tropikal tohum serisiyle tanışın. 🌴✨",
    status: "NEEDS_REVIEW",
    statusLabel: "Askıda olması",
    campaignName: "Egzotik Seri",
    tags: ["papaya", "tropikal", "yenilik"],
    platform: "instagram",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-3",
    title: "Güne enerjik bir başlangıç: Taze limon ferahlığı.",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 08:30",
    fullDateLabel: "6 Eylül, 08:30",
    imageUrl: "/images/approvals/lemons_pink.jpg",
    caption: "Günün ilk ışıklarıyla gelen buz gibi lezzet! Doğal narenciye aroması gün boyu enerjinizi yüksek tutar. 🍋💛",
    status: "NEEDS_REVIEW",
    statusLabel: "Askıda olması",
    campaignName: "Sabah Rutini",
    tags: ["limon", "enerji", "jusco"],
    platform: "x",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-4",
    title: "Hafta sonu buluşmaları için serinletici kokteyl tarifleri.",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 17:15",
    fullDateLabel: "7 Eylül, 17:15",
    imageUrl: "/images/approvals/grapefruit_citrus.jpg",
    imageIsVideo: true,
    caption: "Arkadaşlarınla toplanacağın akşamlar için Jusco Greyfurt ile hazırlayabileceğin pratik mocktail tarifleri bio'daki linkte! 🍹",
    status: "NEEDS_REVIEW",
    statusLabel: "Askıda olması",
    campaignName: "Mocktail Serisi",
    tags: ["mocktail", "haftasonu", "tarif"],
    platform: "instagram",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-5",
    title: "Doğallıktan ödün vermeyenler için %100 saf lezzet.",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 19:00",
    fullDateLabel: "8 Eylül, 19:00",
    imageUrl: "/images/approvals/orange_slices.jpg",
    caption: "Katkısız, koruyucusuz ve doğrudan dalından sofranıza gelen narenciye büyüsü. Jusco kalitesiyle tanışın. 🍊🌿",
    status: "NEEDS_REVIEW",
    statusLabel: "Askıda olması",
    campaignName: "Doğal Seri",
    tags: ["saf", "dogal", "narenciye"],
    platform: "linkedin",
    comments: [],
    isDemo: true,
  },

  // Column 2: Geri bildirim bırakıldı
  {
    id: "demo-6",
    title: "Taze ve lezzetli bir şeye mi ihtiyacınız var? 🍋 Biz...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 21:40",
    fullDateLabel: "Sep 10, 09:40 F",
    imageUrl: "/images/approvals/lemons_pink.jpg",
    caption: "Need something fresh & tasty? 🍋 We got your back. All you gotta do is squeeze the day with #JuscoCitrusSoda!",
    status: "FEEDBACK_GIVEN",
    statusLabel: "Askıda olması",
    campaignName: "Limon Lansmanı",
    tags: ["citrus", "summer", "jusco"],
    platform: "instagram",
    comments: [
      {
        id: "c-1",
        authorName: "Sen",
        avatarText: "O",
        timeAgo: "11h",
        text: "The caption is a bit long for IG. Can we trim it and let the visual do more of the talking?",
        isCurrentUser: true,
      },
    ],
    isDemo: true,
  },
  {
    id: "demo-7",
    title: "Bir sonraki lezzetli tatilinize hazır mısınız? 🏖️ İtalya'da spagetti mi...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 21:40",
    fullDateLabel: "Sep 11, 14:20",
    imageUrl: "/images/approvals/pineapple_summer.jpg",
    caption: "Bir sonraki lezzetli tatilinize hazır mısınız? 🏖️ İtalya'da spagetti mi, yoksa buz gibi tropik bir ananas ferahlığı mı? Yaz hiç bitmesin!",
    status: "FEEDBACK_GIVEN",
    statusLabel: "Askıda olması",
    campaignName: "Yaz Kampanyası",
    tags: ["tatil", "ananas", "summer"],
    platform: "instagram",
    comments: [
      {
        id: "c-2",
        authorName: "Elif K.",
        avatarText: "E",
        timeAgo: "1 gün önce",
        text: "Görsel kompozisyonu harika, ama metindeki İtalya referansı yerine Akdeniz sahilleri mi desek?",
        isCurrentUser: false,
      },
    ],
    isDemo: true,
  },
  {
    id: "demo-8",
    title: "Meyve tutkunları buraya: Orman meyveli smoothie deneyimi!",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 21:44",
    fullDateLabel: "Sep 12, 16:50",
    imageUrl: "/images/approvals/smoothie_jars.jpg",
    caption: "Böğürtlen, çilek ve yaban mersini buluştu. Antioksidan deposu Jusco Berry Smoothie şimdi satış noktalarında! 🫐🍓",
    status: "FEEDBACK_GIVEN",
    statusLabel: "Askıda olması",
    campaignName: "Berry Bliss",
    tags: ["berry", "smoothie", "saglik"],
    platform: "x",
    comments: [
      {
        id: "c-3",
        authorName: "Ahmet V.",
        avatarText: "A",
        timeAgo: "3 sa önce",
        text: "Satış noktası etiketlerini de ekleyelim lütfen.",
        isCurrentUser: false,
      },
    ],
    isDemo: true,
  },
  {
    id: "demo-9",
    title: "Narenciye aromasını ikiye katlayan özel tarifler.",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 11:20",
    fullDateLabel: "Sep 13, 11:20",
    imageUrl: "/images/approvals/grapefruit_citrus.jpg",
    caption: "Yaz akşamı partileriniz için evde Jusco ile yapabileceğiniz alkolsüz ferahlatıcı kokteyl önerileri. 🥂🍋",
    status: "FEEDBACK_GIVEN",
    statusLabel: "Askıda olması",
    campaignName: "Parti Serisi",
    tags: ["parti", "ferah", "kokteyl"],
    platform: "facebook",
    comments: [
      {
        id: "c-4",
        authorName: "Sen",
        avatarText: "O",
        timeAgo: "5 sa önce",
        text: "Görselin parlaklığını biraz daha açabilir miyiz?",
        isCurrentUser: true,
      },
    ],
    isDemo: true,
  },

  // Column 3: Onaylı
  {
    id: "demo-10",
    title: "Jusco Citrus'un lezzetini asla hafife almayın. 🤤",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 21:41",
    fullDateLabel: "Sep 16, 09:41 F",
    imageUrl: "/images/approvals/orange_slices.jpg",
    caption: "Never underestimate the tastiness of Jusco Citrus. 🤤",
    status: "APPROVED",
    statusLabel: "Onaylı",
    campaignName: "Ana Marka",
    tags: ["citrus", "orange", "jusco"],
    platform: "instagram",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-11",
    title: "#JuscoSmoothies'lerinize hangi yaratıcı malzemeleri ekliyorsunuz?",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 21:45",
    fullDateLabel: "Sep 17, 10:30",
    imageUrl: "/images/approvals/smoothie_jars.jpg",
    imageIsVideo: true,
    caption: "#JuscoSmoothies'lerinize hangi yaratıcı malzemeleri ekliyorsunuz? Yaban mersini, mango veya kivi? En yaratıcı tarifi yoruma bekliyoruz! 🥝✨",
    status: "APPROVED",
    statusLabel: "Onaylı",
    campaignName: "Topluluk Etkileşimi",
    tags: ["smoothie", "yaraticilik", "etkilesim"],
    platform: "x",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-12",
    title: "Tropik rüzgarlar mutfağınızda: Papaya şöleni.",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 21:44",
    fullDateLabel: "Sep 18, 15:45",
    imageUrl: "/images/approvals/papaya_seeds.jpg",
    caption: "Güneşin sıcaklığını hissettiren egzotik tatlar tek bir yudumda. Jusco Tropik ile güne keyifli bir mola verin. 🌴🍹",
    status: "APPROVED",
    statusLabel: "Onaylı",
    campaignName: "Tropik Rüya",
    tags: ["papaya", "tropik", "mola"],
    platform: "instagram",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-13",
    title: "Limonata sevenlere müjde: Yeni şekersiz Jusco Lemon.",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 16:20",
    fullDateLabel: "Sep 19, 16:20",
    imageUrl: "/images/approvals/lemons_pink.jpg",
    caption: "Şekersiz ama dopdolu lezzetli! Sıfır kalori suçluluk duygusu olmadan ferahlığın tadını çıkarın. 🍋✨",
    status: "APPROVED",
    statusLabel: "Onaylı",
    campaignName: "Zero Serisi",
    tags: ["sekersiz", "fit", "limonata"],
    platform: "facebook",
    comments: [],
    isDemo: true,
  },
  {
    id: "demo-14",
    title: "Gözlükleri takın, yaz havasına hazırlanın!",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "Taslak 18:10",
    fullDateLabel: "Sep 20, 18:10",
    imageUrl: "/images/approvals/pineapple_summer.jpg",
    caption: "Masa başı çalışanlar için tatil hissi veren en eğlenceli içecek Jusco Ananas! Moodunuzu yükseltmeye hazır olun. 🍍😎",
    status: "APPROVED",
    statusLabel: "Onaylı",
    campaignName: "Mood Booster",
    tags: ["mood", "ananas", "eglence"],
    platform: "instagram",
    comments: [],
    isDemo: true,
  },
];
