import type { CalendarPost, CalendarMeeting } from "./types";

export const INITIAL_CALENDAR_POSTS: CalendarPost[] = [
  // Sep 1 (Tuesday)
  {
    id: "cal-1",
    title: "O to the M to the G. Check out these mind-blowing lemonade...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "12:54 AM",
    date: "2026-09-01",
    imageUrl: "/images/approvals/grapefruit_citrus.jpg",
    isCarousel: true,
    caption: "O to the M to the G. Check out these mind-blowing lemonade recipes! Friends, sunshine, and chilled Jusco Citrus. #JuscoVibes",
    tags: ["recipes", "Articles"],
    campaignName: null,
    platform: "facebook",
    approvalStatus: "PENDING",
    postStatus: "SCHEDULED",
    commentCount: 2,
    isDemo: true,
    analytics: {
      views: "4.25K",
      reach: "4.10K",
      engagement: "840",
      reactions: { like: 18, love: 22, haha: 5, wow: 8, sad: 1, angry: 0, total: 54 },
      comments: 24,
      shares: 12,
      linkClicks: 32,
      otherClicks: 110,
    },
  },

  // Sep 7 (Monday) - Under "New Flavours Launch" campaign
  {
    id: "cal-2",
    title: "Need something fresh & tasty? We got your back...",
    accountName: "Jusco Citrus Soda +1",
    handle: "juscosoda",
    timeLabel: "09:15 PM",
    date: "2026-09-07",
    imageUrl: "/images/approvals/lemons_pink.jpg",
    imageIsVideo: true,
    caption: "Need something fresh & tasty? 🍋 We got your back. All you gotta do is squeeze the day with #JuscoCitrusSoda!",
    tags: ["Jusco Citrus Soda", "Campaigns"],
    campaignName: "New Flavours Launch",
    platform: "facebook",
    approvalStatus: "PENDING",
    postStatus: "SCHEDULED",
    commentCount: 1,
    isDemo: true,
    analytics: {
      views: "5.80K",
      reach: "5.50K",
      engagement: "920",
      videoPlays: { threeSec: 1240, oneMin: 420, avgMinutes: "0:45" },
      reactions: { like: 45, love: 38, haha: 12, wow: 6, sad: 0, angry: 0, total: 101 },
      comments: 68,
      shares: 24,
      linkClicks: 15,
      otherClicks: 180,
    },
  },

  // Sep 11 (Friday) - Under "New Flavours Launch"
  {
    id: "cal-3",
    title: "Ready for your next delicious vacay? 🏖️ Spaghetti in Italy?...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "09:46 PM",
    date: "2026-09-11",
    imageUrl: "/images/approvals/pineapple_summer.jpg",
    imageIsVideo: true,
    caption: "Ready for your next delicious vacay? 🏖️ Spaghetti in Italy? Paella in Spain? Or icy tropical pineapple refreshment? #JuscoSummer",
    tags: ["Draft", "Summer"],
    campaignName: "New Flavours Launch",
    platform: "facebook",
    approvalStatus: "PENDING",
    postStatus: "DRAFT",
    commentCount: 3,
    isDemo: true,
    analytics: {
      views: "6.40K",
      reach: "6.12K",
      engagement: "980",
      videoPlays: { threeSec: 940, oneMin: 310, avgMinutes: "0:38" },
      reactions: { like: 52, love: 41, haha: 8, wow: 11, sad: 2, angry: 1, total: 115 },
      comments: 84,
      shares: 31,
      linkClicks: 18,
      otherClicks: 195,
    },
  },

  // Sep 12 (Saturday) - Post 1 (Pineapple Queen)
  {
    id: "cal-4",
    title: "Jusco Pineapple Queen - 100% juice, 100% magic...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "11:59 PM",
    date: "2026-09-12",
    imageUrl: "/images/approvals/orange_slices.jpg",
    caption: "Jusco Pineapple Queen 🍍 - 100% juice, 100% magic. Now it's easy to boost your weekend with pure vitamin punch!",
    tags: ["Approved"],
    campaignName: "New Flavours Launch",
    platform: "facebook",
    approvalStatus: "APPROVED",
    postStatus: "SCHEDULED",
    commentCount: 4,
    isDemo: true,
    analytics: {
      views: "7.13K",
      reach: "7.13K",
      engagement: "1.11K",
      videoPlays: { threeSec: 0, oneMin: 0, avgMinutes: "0:00" },
      reactions: { like: 6, love: 14, haha: 27, wow: 3, sad: 41, angry: 39, total: 130 },
      comments: 759,
      shares: 42,
      linkClicks: 0,
      otherClicks: 306,
    },
  },

  // Sep 12 (Saturday) - Post 2 (Casual drinks / cocktail)
  {
    id: "cal-5",
    title: "From casual drinks to the summer's ultimate cocktail...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "11:59 PM",
    date: "2026-09-12",
    imageUrl: "/images/approvals/grapefruit_citrus.jpg",
    imageIsVideo: true,
    caption: "From casual drinks to the summer's ultimate cocktail, Jusco's here to save the day. Check out our video for DIY recipes and party tips. #DrinkTheSummer",
    tags: ["Engagement posts"],
    campaignName: "New Flavours Launch",
    platform: "facebook",
    approvalStatus: "APPROVED",
    postStatus: "PUBLISHED",
    commentCount: 12,
    isDemo: true,
    analytics: {
      views: "7.13K",
      reach: "7.13K",
      engagement: "1.11K",
      videoPlays: { threeSec: 2100, oneMin: 850, avgMinutes: "1:15" },
      reactions: { like: 6, love: 14, haha: 27, wow: 3, sad: 41, angry: 39, total: 130 },
      comments: 759,
      shares: 42,
      linkClicks: 0,
      otherClicks: 306,
    },
  },

  // Sep 12 (Saturday) - Post 3 (Promotion)
  {
    id: "cal-6",
    title: "Open. Sip. Smile. Repeat. 🥤",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "11:59 PM",
    date: "2026-09-12",
    imageUrl: "/images/approvals/smoothie_jars.jpg",
    imageIsVideo: true,
    caption: "Open. Sip. Smile. Repeat. Get 20% off all Jusco variety packs this weekend only with code FRESH20!",
    tags: ["Promotion"],
    campaignName: "New Flavours Launch",
    platform: "facebook",
    approvalStatus: "APPROVED",
    postStatus: "SCHEDULED",
    commentCount: 0,
    isDemo: true,
    analytics: {
      views: "3.80K",
      reach: "3.60K",
      engagement: "610",
      videoPlays: { threeSec: 1100, oneMin: 280, avgMinutes: "0:25" },
      reactions: { like: 32, love: 28, haha: 4, wow: 2, sad: 0, angry: 0, total: 66 },
      comments: 15,
      shares: 8,
      linkClicks: 45,
      otherClicks: 120,
    },
  },

  // Sep 13 (Sunday) - Post 1 (Green bottle / greens)
  {
    id: "cal-7",
    title: "Can't have the blues once you taste the greens...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "09:41 PM",
    date: "2026-09-13",
    imageUrl: "/images/approvals/papaya_seeds.jpg",
    caption: "Can't have the blues once you taste the greens. Guaranteed. Have you tasted our cold-pressed green boost?",
    tags: ["Healthy"],
    campaignName: "New Flavours Launch",
    platform: "instagram",
    approvalStatus: "APPROVED",
    postStatus: "SCHEDULED",
    commentCount: 4,
    isDemo: true,
    analytics: {
      views: "4.90K",
      reach: "4.75K",
      engagement: "810",
      reactions: { like: 62, love: 45, haha: 3, wow: 12, sad: 0, angry: 0, total: 122 },
      comments: 48,
      shares: 16,
      linkClicks: 22,
      otherClicks: 140,
    },
  },

  // Sep 13 (Sunday) - Post 2 (Citrus explosion)
  {
    id: "cal-8",
    title: "I've never experienced an explosion of flavors like this one...",
    accountName: "Jusco",
    handle: "juscosoda",
    timeLabel: "09:43 PM",
    date: "2026-09-13",
    imageUrl: "/images/approvals/orange_slices.jpg",
    caption: "“I've never experienced an explosion of flavors like this one” - Jusco customer review. Try it today!",
    tags: ["Campaigns"],
    campaignName: "New Flavours Launch",
    platform: "facebook",
    approvalStatus: "APPROVED",
    postStatus: "PUBLISHED",
    commentCount: 1,
    isDemo: true,
    analytics: {
      views: "5.10K",
      reach: "4.90K",
      engagement: "780",
      reactions: { like: 58, love: 36, haha: 5, wow: 8, sad: 0, angry: 0, total: 107 },
      comments: 32,
      shares: 14,
      linkClicks: 28,
      otherClicks: 135,
    },
  },
];

export const CALENDAR_MEETINGS: CalendarMeeting[] = [
  {
    id: "meet-1",
    title: "Content Review Meeting",
    time: "1:00 - 2:00 PM",
    date: "2026-09-13",
  },
];
